import KeycloakProviderWrapper from '@/providers/KeycloakProviderWrapper';
import { QueryProvider } from '@/providers/QueryProvider';
import { ThemeProvider } from '@/providers/ThemeProvider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import React from 'react';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ChatPopup from '@/components/ChatPopup';
import ChatProvider from '@/providers/ChatProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Geardotcom',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <KeycloakProviderWrapper>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ToastContainer />
              <Header />
              <ChatProvider>{children}</ChatProvider>
            </ThemeProvider>
          </QueryProvider>
        </KeycloakProviderWrapper>
      </body>
    </html>
  );
}
